name: SpawnerItemFrame
version: '0.2.1'
main: ru.m9studio.SpawnerItemFrame.SpawnerItemFrame
api-version: '1.20'
author: mina987
authors: [mina987, voldmaks]
website: www.m9-studio.ru
load: POSTWORLD
softdepend: [ItemsAdder]
description: Spawn items in the ItemFrames